# Generated by Django 4.2.2 on 2023-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_profile_date_of_lastquiz_profile_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.BigIntegerField(),
        ),
    ]
