# Generated by Django 4.2.2 on 2023-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_profile_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
