# Generated by Django 4.2.8 on 2024-01-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_category_quizresult_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='username',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizapp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
