# Generated by Django 4.2.2 on 2023-12-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_lastquiz',
        ),
    ]
