# Generated by Django 4.2.8 on 2024-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_remove_quizresult_username_quizresult_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='Category',
            field=models.IntegerField(),
        ),
    ]
