# Generated by Django 4.2.8 on 2024-01-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_questionwithparts_partsofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='mental_status',
            field=models.CharField(max_length=1000),
        ),
    ]
