# Generated by Django 4.2.8 on 2024-02-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_alter_quizresult_mental_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('id', 'Category')},
        ),
    ]
