# Generated by Django 4.2.8 on 2024-02-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_quizresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizresult',
            name='unique_id_category',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.category'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('id', 'Category')},
        ),
    ]
