# Generated by Django 4.2.8 on 2024-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_result_delete_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo1', models.ImageField(upload_to='home_photos/')),
                ('photo2', models.ImageField(upload_to='home_photos/')),
            ],
        ),
    ]
