# Generated by Django 4.2.8 on 2024-03-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_home_text1_home_text2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Home_page',
        ),
    ]
