# Generated by Django 4.2.8 on 2024-03-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_rename_home_home_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_page',
            options={'verbose_name': 'Home Page (frontend)'},
        ),
    ]
