# Generated by Django 4.2.8 on 2024-03-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_alter_home_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_page',
            options={'verbose_name_plural': 'Home Page (frontend)'},
        ),
    ]
