# Generated by Django 4.2.8 on 2024-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='how_do_you_feel_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('link1', models.CharField(max_length=500)),
                ('link2', models.CharField(max_length=500)),
                ('link3', models.CharField(max_length=500)),
                ('link4', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': '¿Cómo te sientes hoy? Page (frontend)',
            },
        ),
    ]
