# Generated by Django 4.2.8 on 2024-03-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0019_how_do_you_feel_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1_name', models.CharField(max_length=100)),
                ('person1_description', models.TextField()),
                ('photo1', models.ImageField(upload_to='about_photos/')),
                ('person2_name', models.CharField(max_length=100)),
                ('person2_description', models.TextField()),
                ('photo2', models.ImageField(upload_to='about_photos/')),
                ('person3_name', models.CharField(max_length=100)),
                ('person3_description', models.TextField()),
                ('photo3', models.ImageField(upload_to='about_photos/')),
            ],
        ),
    ]
