# Generated by Django 4.2.8 on 2024-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0021_result_anxiety_page_result_autostima_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anxiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='anxiety_photos/')),
                ('Instruction_Text', models.TextField()),
                ('Instruction_option1', models.CharField(max_length=200)),
                ('Instruction_option2', models.CharField(max_length=200)),
                ('Instruction_option3', models.CharField(max_length=200)),
                ('Instruction_option4', models.CharField(max_length=200)),
                ('link1', models.CharField(max_length=500)),
                ('link2', models.CharField(max_length=500)),
                ('link3', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Anxiety Page (frontend)',
            },
        ),
        migrations.CreateModel(
            name='Autostima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='autostima_photos/')),
                ('Instruction_Text', models.TextField()),
                ('Instruction_option1', models.CharField(max_length=200)),
                ('Instruction_option2', models.CharField(max_length=200)),
                ('Instruction_option3', models.CharField(max_length=200)),
                ('Instruction_option4', models.CharField(max_length=200)),
                ('link1', models.CharField(max_length=500)),
                ('link2', models.CharField(max_length=500)),
                ('link3', models.CharField(max_length=500)),
                ('link4', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Autoestima Page (frontend)',
            },
        ),
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='depression_photos/')),
                ('Instruction_Text', models.TextField()),
                ('Instruction_option1', models.CharField(max_length=200)),
                ('Instruction_option2', models.CharField(max_length=200)),
                ('Instruction_option3', models.CharField(max_length=200)),
                ('Instruction_option4', models.CharField(max_length=200)),
                ('link1', models.CharField(max_length=500)),
                ('link2', models.CharField(max_length=500)),
                ('link3', models.CharField(max_length=500)),
                ('link4', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Depression Page (frontend)',
            },
        ),
        migrations.CreateModel(
            name='oriention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='oriention_photos/')),
                ('Instruction_Text', models.TextField()),
                ('Instruction_option1', models.CharField(max_length=200)),
                ('Instruction_option2', models.CharField(max_length=200)),
                ('Instruction_option3', models.CharField(max_length=200)),
                ('Instruction_option4', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Orientación Vocacional Page (frontend)',
            },
        ),
        migrations.AlterModelOptions(
            name='result_autostima_page',
            options={'verbose_name_plural': 'Autoestima Result Page (frontend)'},
        ),
    ]
