# Generated by Django 4.2.8 on 2024-03-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0023_anxiety_quiz_page_autostima_quiz_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autostima_quiz_page',
            options={'verbose_name_plural': 'Autoestima quiz Page (frontend)'},
        ),
        migrations.AlterModelOptions(
            name='oriention_quiz_page',
            options={'verbose_name_plural': 'Orientación quiz Page (frontend)'},
        ),
        migrations.AlterModelOptions(
            name='result_oriention_page',
            options={'verbose_name_plural': 'Orientación Result Page (frontend)'},
        ),
    ]
